services:
  caddy:
    # build: ./caddy
    restart: unless-stopped
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11092505-my-assignment-repo:caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - caddy:/data

  frontend:
    restart: unless-stopped
    # build: ./frontend
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11092505-my-assignment-repo:frontend

  
  backend:
    restart: unless-stopped
    # build: ./backend
    image: 901444280953.dkr.ecr.ap-southeast-2.amazonaws.com/n11092505-my-assignment-repo:backend
    environment:
      - ORIGIN=https://ilovequt.lol
    volumes:
      - db:/api/storage
  
  dns-updater:
    build: ./dns-updater
    restart: unless-stopped

volumes:
  db:
    name: backend-db
  caddy:
    name: caddy-data
